[translator fail issue] translator fail issued solved.
Added xml-apis-1.4.01.jar to solve the translator fail issue. This issue
is caused by NoClassDefFoundError of org.w3c.dom.ElementTraversal.